framework:
    rate_limiter:
        burn_note:
            policy: sliding_window
            limit: 20
            interval: '1 minute'
        burn_note_create:
            policy: sliding_window
            limit: 10
            interval: '1 minute'
        csr_generate:
            policy: sliding_window
            limit: 20
            interval: '1 minute'
